### PR TITLE
Fix typos and confusing wording in documentation

### PR DESCRIPTION
**Pull request by ginic**
Hi satellite imagery tool team! 
I hope this tool still has some support, because my team at UMass Amherst think it's great and would like to use and improve it. 

This pull request is just to polish the documentation for this project. There are no substantive changes, just cleaning up what's already there. 

What's included:
- Clarify some wording and what's being referred to, especially in docs/Labeler.md and docs/Project-builder.md
- Fixing typos and misspellings
- Removing trailing whitespace in markdown file

### CODE REVIEW

**Comment by rbrundritt** [comment]
Thanks

**Comment by calebrob6** [comment]
Awesome, thank you @ginic!

**Comment by ginic** [comment]
No problem! 

Would you mind telling me what you're using to bundle and serve this tool? I wasn't able to find those details in the docs. 

I'm currently serving using https://parceljs.org/ with some minor code changes, but that introduces a dependency on Node.js/npm, which it sounded like you were trying to avoid.

**Comment by rbrundritt** [comment]
There is no bundling used in this project at this time. Many of the users are non-developers, so we kept it simple HTML/JS files, with no need for a build/bundling script or tools.

**Comment by ginic** [comment]
That makes sense. However, when I opened the projectBuilder.html without starting a local web server, none of the features worked for me, and I wasn't even able to get past the first `Next` button to create a project. The error I saw was `Module source URI is not allowed in this document: “file:///home/virginia/workspace/satellite-imagery-labeling-tool/src/modules/projectBuilder.js”`
Screenshot from 2023-02-01 15-47-16

**Comment by rbrundritt** [comment]
Yes. We eventually had to get to that point as this project grew. In the last major version update we started using JS modules and web workers which require running the site on local host. VS code with the "Go live" extension is a pretty easy option. With V2 we also started hosting a version of this tool as github.io pages so others don't need to worry about hosting it.

**Comment by ginic** [comment]
Okay, thanks for the clarification!

**Pull request merged**
